(()=>{const S={step:1,total:7,style:"elegante",photo:null},$=id=>document.getElementById(id),steps=[...document.querySelectorAll(".form-step")];
function boot(){bind();renderStep();updatePreview();addHighlight();renderLocalGallery()}
function bind(){$("choosePhoto").onclick=()=>$("photo").click();$("uploadZone").onclick=e=>{if(e.target.tagName!=="BUTTON"&&e.target.id!=="photoPreview")$("photo").click()};$("photo").onchange=e=>{const f=e.target.files[0];if(!f)return;if(!/^image\/(jpeg|png|webp)$/.test(f.type))return msg("Use JPG, PNG ou WEBP.");if(f.size>8*1024*1024)return msg("A foto deve ter no máximo 8 MB.");S.photo=f;$("photoPreview").src=URL.createObjectURL(f);$("photoPreview").classList.remove("hidden");$("photoPlaceholder").classList.add("hidden")};$("story").oninput=e=>$("storyCount").textContent=e.target.value.length;$("addHighlight").onclick=()=>addHighlight();$("visualLocation").onchange=()=>$("otherLocationWrap").classList.toggle("hidden",$("visualLocation").value!=="other");document.querySelectorAll(".style-option").forEach(b=>b.onclick=()=>{document.querySelectorAll(".style-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");S.style=b.dataset.style});$("nextBtn").onclick=next;$("backBtn").onclick=back;$("tagForm").onsubmit=generate;$("regenerateBtn").onclick=()=>{$("resultSection").classList.add("hidden");window.scrollTo({top:0,behavior:"smooth"})};["displayName","city","state","gender"].forEach(id=>$(id).addEventListener("input",updatePreview));$("refreshGallery").onclick=renderLocalGallery}
function addHighlight(v=""){const r=document.createElement("div");r.className="highlight-row";r.innerHTML='<input maxlength="120" placeholder="Ex.: Mais de 10 anos de experiência"><button type="button" class="remove-highlight">×</button>';r.querySelector("input").value=v;r.querySelector("button").onclick=()=>r.remove();$("highlights").appendChild(r)}
function next(){if(S.step===1&&!S.photo)return msg("Envie sua foto para continuar.");if(S.step<S.total){S.step++;renderStep()}}
function back(){if(S.step>1){S.step--;renderStep()}}
function renderStep(){steps.forEach((x,i)=>x.classList.toggle("active",i+1===S.step));$("stepNumber").textContent=S.step;$("stepTitle").textContent=["Sua foto","Sua identidade","Sua história","Destaques","Frase","Localização","Estilo"][S.step-1];$("progressFill").style.width=S.step/S.total*100+"%";$("backBtn").classList.toggle("hidden",S.step===1);$("nextBtn").classList.toggle("hidden",S.step===S.total);$("generateBtn").classList.toggle("hidden",S.step!==S.total);updatePreview()}
function updatePreview(){const n=$("displayName").value||"Seu nome",c=$("city").value||"Cidade",u=$("state").value||"UF",g=$("gender").value;$("pvName").textContent=n;$("pvLocation").textContent=c+" · "+u;$("pvKicker").textContent=g==="male"?"CONHEÇA NOSSO EMBAIXADOR":g==="neutral"?"CONHEÇA NOSSO REPRESENTANTE":"CONHEÇA NOSSA EMBAIXADORA"}
function collect(){return{fullName:$("fullName").value.trim(),displayName:$("displayName").value.trim(),profession:$("profession").value.trim(),city:$("city").value.trim(),state:$("state").value.trim().toUpperCase(),birthPlace:$("birthPlace").value.trim(),story:$("story").value.trim(),highlights:[...document.querySelectorAll("#highlights input")].map(x=>x.value.trim()).filter(Boolean),quote:$("quote").value.trim(),visualLocation:$("visualLocation").value,otherLocation:$("otherLocation").value.trim(),gender:$("gender").value,style:S.style}}
function fitText(ctx,text,maxWidth,maxSize,minSize){for(let size=maxSize;size>=minSize;size-=2){ctx.font="700 "+size+"px Arial";if(ctx.measureText(text).width<=maxWidth)return size}return minSize}
function wrap(ctx,text,maxWidth){const words=String(text||"").split(/\s+/),lines=[];let line="";for(const w of words){const t=line?line+" "+w:w;if(ctx.measureText(t).width>maxWidth&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);return lines}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function compressPhoto(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{const max=1600,r=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=Math.round(i.width*r);c.height=Math.round(i.height*r);c.getContext("2d").drawImage(i,0,0,c.width,c.height);URL.revokeObjectURL(u);c.toBlob(b=>{if(!b)return reject(Error("compress"));const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(b)},"image/jpeg",.88)};i.onerror=reject;i.src=u})}
function drawText(ctx,d,W,H){const dark=d.style!=="minimalista";ctx.fillStyle=dark?"rgba(8,6,4,.78)":"rgba(255,255,255,.84)";ctx.fillRect(0,H*.58,W,H*.42);ctx.fillStyle=dark?"#d9bd91":"#8d6333";ctx.font="700 18px Arial";ctx.fillText("ANE CAKES FAIR",62,80);const title=d.gender==="male"?"CONHEÇA NOSSO EMBAIXADOR":d.gender==="neutral"?"CONHEÇA NOSSO REPRESENTANTE":"CONHEÇA NOSSA EMBAIXADORA";ctx.fillStyle=dark?"#fff":"#181512";ctx.font="600 23px Arial";ctx.fillText(title,62,115);ctx.fillStyle=dark?"#fff":"#181512";const ns=fitText(ctx,d.displayName,760,74,40);ctx.font="700 "+ns+"px Arial";ctx.fillText(d.displayName,62,690);ctx.fillStyle=dark?"#e2c99e":"#8d6333";ctx.font="600 25px Arial";ctx.fillText(d.profession,62,728);ctx.fillStyle=dark?"#fff":"#181512";ctx.font="500 20px Arial";ctx.fillText(d.city+" · "+d.state,62,758);ctx.font="400 18px Arial";const story=wrap(ctx,d.story,930).slice(0,3);story.forEach((l,i)=>ctx.fillText(l,62,805+i*25));let y=900;ctx.fillStyle=dark?"#d9bd91":"#8d6333";ctx.font="700 16px Arial";d.highlights.slice(0,3).forEach((h,i)=>{ctx.fillText("• "+h,62,y+i*24)});const q=d.quote||"Onde a confeitaria vira experiência.";ctx.fillStyle=dark?"#fff":"#181512";ctx.font="italic 20px Georgia";wrap(ctx,q,900).slice(0,2).forEach((l,i)=>ctx.fillText("“"+l+(i===1?"”":""),62,1010+i*27));ctx.fillStyle=dark?"#d9bd91":"#8d6333";ctx.font="700 13px Arial";ctx.fillText("EMBAIXADOR(A) OFICIAL DA ANE CAKES FAIR",62,1070)}
async function renderFinal(aiUrl,d){const ai=await loadImage(aiUrl),W=1080,H=1350,c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=W;c.height=H;const scale=Math.max(W/ai.width,H/ai.height),w=ai.width*scale,h=ai.height*scale;ctx.drawImage(ai,(W-w)/2,(H-h)/2,w,h);drawText(ctx,d,W,H);return c.toDataURL("image/png")}
async function localFallback(d){const u=URL.createObjectURL(S.photo),img=await loadImage(u),W=1080,H=1350,c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=W;c.height=H;const gr=ctx.createLinearGradient(0,0,W,H);gr.addColorStop(0,"#17130f");gr.addColorStop(1,"#66513c");ctx.fillStyle=gr;ctx.fillRect(0,0,W,H);const r=Math.max(W/img.width,H/img.height),w=img.width*r,h=img.height*r;ctx.drawImage(img,(W-w)/2,(H-h)/2,w,h);ctx.fillStyle="rgba(8,6,4,.75)";ctx.fillRect(0,700,W,650);drawText(ctx,d,W,H);URL.revokeObjectURL(u);return c.toDataURL("image/png")}
async function generate(e){e.preventDefault();if(!S.photo)return msg("Envie sua foto.");const d=collect();if(!d.displayName||!d.profession||!d.city||!d.state)return msg("Preencha nome, profissão, cidade e estado.");$("generateBtn").disabled=true;$("generateBtn").textContent="✨ A IA está criando...";msg("Analisando sua foto e criando uma composição personalizada...");try{const photoDataUrl=await compressPhoto(S.photo);const response=await fetch("/api/generate-card",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...d,photoDataUrl})});let aiUrl="";if(response.ok){const payload=await response.json();aiUrl=payload.imageDataUrl}else{const payload=await response.json().catch(()=>({}));if(response.status!==503&&response.status!==429)console.warn(payload.error)}const finalUrl=aiUrl?await renderFinal(aiUrl,d):await localFallback(d);$("resultImage").src=finalUrl;$("downloadBtn").href=finalUrl;$("downloadBtn").download="ane-cakes-"+(d.displayName||"embaixador").replace(/[^a-z0-9]+/gi,"-").toLowerCase()+".png";$("resultSection").classList.remove("hidden");$("resultSection").scrollIntoView({behavior:"smooth"});saveLocal(d,finalUrl);msg(aiUrl?"Arte criada com inteligência artificial!":"Arte criada no modo automático enquanto a IA não está configurada no servidor.","success");renderLocalGallery()}catch(err){console.error(err);msg("Não foi possível criar a arte. Tente novamente.")}finally{$("generateBtn").disabled=false;$("generateBtn").textContent="✨ Gerar minha arte"}}
function saveLocal(d,url){const list=JSON.parse(localStorage.getItem("aneCakesCards")||"[]");list.unshift({name:d.displayName,image:url,style:d.style,date:new Date().toISOString(),ai:true});localStorage.setItem("aneCakesCards",JSON.stringify(list.slice(0,12)))}
function renderLocalGallery(){const list=JSON.parse(localStorage.getItem("aneCakesCards")||"[]");$("gallery").innerHTML=list.length?list.map(x=>'<article class="gallery-card"><img src="'+x.image+'" alt="Arte de '+esc(x.name)+'"><div class="gallery-card-body"><strong>'+esc(x.name)+'</strong><small>'+esc(x.style||"")+ " · "+new Date(x.date).toLocaleDateString("pt-BR")+"</small></div></article>").join(""):'<p class="empty-state">Suas artes criadas neste dispositivo aparecerão aqui.</p>'}
function msg(t,c=""){$("formMessage").textContent=t;$("formMessage").className="form-message "+c}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
boot()})();