/* Ane Cakes Fair — tradução nativa, sem Google Translate. */
(function(){
  const LANGS=['pt','en','es'];
  let DICT={};
  const originals=new WeakMap();
  const SKIP=new Set(['SCRIPT','STYLE','NOSCRIPT','TEXTAREA','OPTION']);
  const normalize=s=>s.replace(/\s+/g,' ').trim();
  const preserve=(original,translated)=>{const lead=(original.match(/^\s*/)||[''])[0],trail=(original.match(/\s*$/)||[''])[0];return lead+translated+trail};

  /* Traduções complementares das páginas internas. O conteúdo continua no próprio site. */
  const EXTRA={
    en:{
      'Parceiros':'Partners','Equipe':'Team','Caravanas':'Caravans','Expositores':'Exhibitors','Batalha Doce':'Sweet Battle','Roteiro':'Schedule','Embaixadora':'Ambassador','Início':'Home',
      '5ª EDIÇÃO · ILHÉUS, BAHIA · DA ORIGEM AO DESTINO':'5TH EDITION · ILHÉUS, BAHIA · FROM ORIGIN TO DESTINATION',
      '5ª EDIÇÃO · ILHÉUS, BAHIA · 30 DE NOVEMBRO DE 2026':'5TH EDITION · ILHÉUS, BAHIA · NOVEMBER 30, 2026',
      'Capacitação que vira profissão. · Talento que vira negócio.':'Training that becomes a profession. · Talent that becomes business.',
      'VISIT THE ORIGIN · ILHÉUS · COSTA DO CACAU':'VISIT THE ORIGIN · ILHÉUS · COCOA COAST',
      'Você experimentou o Brasil. Agora descubra onde essa história começa.':'You experienced Brazil. Now discover where this story begins.',
      'Uma história em movimento':'A story in motion','Antes de conhecer o território, conheça a história.':'Before discovering the territory, discover the story.',
      'Descobrir o Cupuaçu':'Discover Cupuaçu','Território, fruto e biodiversidade':'Territory, fruit and biodiversity','Do ingrediente às possibilidades':'From ingredient to possibilities','Novas receitas e aplicações':'New recipes and applications','Conhecimento encontra público':'Knowledge meets the public','Experimentar para descobrir':'Experiment to discover','Descobrir desde cedo':'Discover from an early age','Encontro de territórios':'Meeting of territories','Fazendas de cacau':'Cocoa farms','Chocolate & gastronomia':'Chocolate & gastronomy','Cultura & natureza':'Culture & nature','Hospedagem & experiências':'Accommodation & experiences',
      'Business Arena':'Business Arena','A cultura cria valor. O mercado cria negócios.':'Culture creates value. The market creates business.',
      'Brazil to the World':'Brazil to the World','O sabor brasileiro pode ser uma ponte para o mundo.':'Brazilian flavor can be a bridge to the world.',
      'Acesso, formação e legado':'Access, training and legacy','O conhecimento não termina quando as portas se fecham.':'Knowledge does not end when the doors close.',
      'Começamos pela confeitaria. Chegamos ao território.':'We started with pastry. We reached the territory.',
      'Parceiros que tornam sonhos possíveis.':'Partners who make dreams possible.','Quero ser parceiro':'I want to be a partner','Conexões que transformam ideias em oportunidades.':'Connections that turn ideas into opportunities.','Parceria com a Prefeitura e o Sebrae':'Partnership with the City Hall and Sebrae',
      'As pessoas por trás da transformação.':'The people behind the transformation.','Uma história construída por pessoas':'A story built by people','Da capacitação à transformação.':'From training to transformation.','A equipe em movimento':'The team in motion','Uma história que também pode ser vista.':'A story that can also be seen.','O que descobrimos':'What we discovered','Por trás de cada criação existe uma cadeia inteira.':'Behind every creation there is an entire chain.',
      'Venha viver essa experiência junto.':'Come live this experience together.','Organize sua caravana e participe do maior encontro de confeitaria, empreendedorismo e oportunidades da região.':'Organize your group and join the region’s biggest gathering of pastry, entrepreneurship and opportunities.','Cadastrar caravana':'Register your group',
      'Mais do que stands. Uma cadeia inteira.':'More than stands. An entire chain.','Uma feira construída por conexões.':'A fair built through connections.','Quem precisa estar na feira':'Who needs to be at the fair','A experiência do visitante':'The visitor experience','A jornada do visitante':'The visitor’s journey','Entrar, descobrir, aprender e sair diferente.':'Enter, discover, learn and leave transformed.','Seu trabalho pode fazer parte da jornada.':'Your work can be part of the journey.','Quero participar →':'I want to participate →','Quero expor →':'I want to exhibit →',
      'Batalha Doce.':'Sweet Battle.','Uma experiência para celebrar a confeitaria brasileira como espaço de técnica, criatividade, identidade e descoberta — conectando ingredientes, saberes e pessoas por meio da criação.':'An experience celebrating Brazilian pastry as a space for technique, creativity, identity and discovery — connecting ingredients, knowledge and people through creation.','Inscrições e regulamento em breve':'Registration and rules coming soon','Não é apenas uma competição.':'It is not just a competition.','Onde o talento encontra a criação.':'Where talent meets creation.','Talento que vira repertório.':'Talent that becomes a repertoire.','Um ingrediente pode abrir uma nova conversa.':'An ingredient can open a new conversation.','Prepare-se para criar.':'Get ready to create.',
      'Dois dias, uma jornada.':'Two days, one journey.','Dois dias para descobrir os sabores, os saberes, as pessoas e as possibilidades que o Brasil oferece.':'Two days to discover the flavors, knowledge, people and possibilities Brazil offers.','Dia 1 · Brasil de Origem':'Day 1 · Brazil of Origin','Dia 2 · Brasil que Cria':'Day 2 · Brazil Creates','Arena de Saberes':'Knowledge Arena','Conhecimento que faz parte da jornada.':'Knowledge that is part of the journey.','Uma narrativa, muitos encontros':'One narrative, many encounters','Não é apenas sobre assistir.':'It is not just about watching.',
      'Uma voz para ampliar o impacto.':'A voice to expand the impact.','A Embaixadora do Ane Cakes Fair representa os valores do evento, inspira a comunidade e ajuda a levar essa transformação ainda mais longe.':'The Ane Cakes Fair Ambassador represents the event’s values, inspires the community and helps take this transformation even further.','Em breve anunciaremos a embaixadora oficial da edição 2026.':'We will soon announce the official ambassador for the 2026 edition.','Quem será a escolhida?':'Who will be chosen?','Cinco nomes, uma grande expectativa. A revelação oficial da primeira embaixadora da Ane Cakes Fair vem aí.':'Five names, one great expectation. The official reveal of the first Ane Cakes Fair ambassador is coming.','Quero saber mais':'I want to know more',
      'Aprender':'Learn','Praticar':'Practice','Apresentar':'Present','Conectar':'Connect','Origem':'Origin','Transformação':'Transformation','Criação':'Creation','Negócios':'Business','Experiência':'Experience','Destino':'Destination','Capacitação':'Training','Profissionalização':'Professionalization','Empreendedorismo':'Entrepreneurship','Conhecer':'Discover','Experimentar':'Experiment','Compartilhar':'Share','Registrar':'Record'
    },
    es:{
      'Parceiros':'Socios','Equipe':'Equipo','Caravanas':'Caravanas','Expositores':'Expositores','Batalha Doce':'Batalla Dulce','Roteiro':'Programa','Embaixadora':'Embajadora','Início':'Inicio',
      '5ª EDIÇÃO · ILHÉUS, BAHIA · DA ORIGEM AO DESTINO':'5ª EDICIÓN · ILHÉUS, BAHÍA · DEL ORIGEN AL DESTINO','5ª EDIÇÃO · ILHÉUS, BAHIA · 30 DE NOVEMBRO DE 2026':'5ª EDICIÓN · ILHÉUS, BAHÍA · 30 DE NOVIEMBRE DE 2026','Capacitação que vira profissão. · Talento que vira negócio.':'Formación que se convierte en profesión. · Talento que se convierte en negocio.',
      'VISIT THE ORIGIN · ILHÉUS · COSTA DO CACAU':'VISIT THE ORIGIN · ILHÉUS · COSTA DEL CACAO','Você experimentou o Brasil. Agora descubra onde essa história começa.':'Has experimentado Brasil. Ahora descubre dónde comienza esta historia.','Uma história em movimento':'Una historia en movimiento','Antes de conhecer o território, conheça a história.':'Antes de conocer el territorio, conoce la historia.',
      'Descobrir o Cupuaçu':'Descubrir el cupuaçu','Território, fruto e biodiversidade':'Territorio, fruto y biodiversidad','Do ingrediente às possibilidades':'Del ingrediente a las posibilidades','Novas receitas e aplicações':'Nuevas recetas y aplicaciones','Conhecimento encontra público':'El conocimiento encuentra al público','Experimentar para descobrir':'Experimentar para descubrir','Descobrir desde cedo':'Descubrir desde temprano','Encontro de territórios':'Encuentro de territorios','Fazendas de cacau':'Fincas de cacao','Chocolate & gastronomia':'Chocolate y gastronomía','Cultura & natureza':'Cultura y naturaleza','Hospedagem & experiências':'Alojamiento y experiencias',
      'Business Arena':'Arena de Negocios','A cultura cria valor. O mercado cria negócios.':'La cultura crea valor. El mercado crea negocios.','Brazil to the World':'Brasil al Mundo','O sabor brasileiro pode ser uma ponte para o mundo.':'El sabor brasileño puede ser un puente hacia el mundo.','Acesso, formação e legado':'Acceso, formación y legado','O conhecimento não termina quando as portas se fecham.':'El conocimiento no termina cuando las puertas se cierran.','Começamos pela confeitaria. Chegamos ao território.':'Comenzamos con la pastelería. Llegamos al territorio.',
      'Parceiros que tornam sonhos possíveis.':'Socios que hacen posibles los sueños.','Quero ser parceiro':'Quiero ser socio','Conexões que transformam ideias em oportunidades.':'Conexiones que transforman ideas en oportunidades.','Parceria com a Prefeitura e o Sebrae':'Alianza con el Ayuntamiento y Sebrae',
      'As pessoas por trás da transformação.':'Las personas detrás de la transformación.','Uma história construída por pessoas':'Una historia construida por personas','Da capacitação à transformação.':'De la formación a la transformación.','A equipe em movimento':'El equipo en movimiento','Uma história que também pode ser vista.':'Una historia que también puede verse.','O que descobrimos':'Lo que descubrimos','Por trás de cada criação existe uma cadeia inteira.':'Detrás de cada creación existe una cadena completa.',
      'Venha viver essa experiência junto.':'Ven a vivir esta experiencia junto.','Organize sua caravana e participe do maior encontro de confeitaria, empreendedorismo e oportunidades da região.':'Organiza tu caravana y participa en el mayor encuentro de pastelería, emprendimiento y oportunidades de la región.','Cadastrar caravana':'Registrar caravana',
      'Mais do que stands. Uma cadeia inteira.':'Más que stands. Una cadena completa.','Uma feira construída por conexões.':'Una feria construida mediante conexiones.','Quem precisa estar na feira':'Quién debe estar en la feria','A experiência do visitante':'La experiencia del visitante','A jornada do visitante':'El viaje del visitante','Entrar, descobrir, aprender e sair diferente.':'Entrar, descubrir, aprender y salir diferente.','Seu trabalho pode fazer parte da jornada.':'Tu trabajo puede formar parte del viaje.','Quero participar →':'Quiero participar →','Quero expor →':'Quiero exponer →',
      'Batalha Doce.':'Batalla Dulce.','Uma experiência para celebrar a confeitaria brasileira como espaço de técnica, criatividade, identidade e descoberta — conectando ingredientes, saberes e pessoas por meio da criação.':'Una experiencia para celebrar la pastelería brasileña como espacio de técnica, creatividad, identidad y descubrimiento — conectando ingredientes, conocimientos y personas mediante la creación.','Inscrições e regulamento em breve':'Inscripciones y reglamento próximamente','Não é apenas uma competição.':'No es solo una competición.','Onde o talento encontra a criação.':'Donde el talento encuentra la creación.','Talento que vira repertório.':'Talento que se convierte en repertorio.','Um ingrediente pode abrir uma nova conversa.':'Un ingrediente puede abrir una nueva conversación.','Prepare-se para criar.':'Prepárate para crear.',
      'Dois dias, uma jornada.':'Dos días, un viaje.','Dois dias para descobrir os sabores, os saberes, as pessoas e as possibilidades que o Brasil oferece.':'Dos días para descubrir los sabores, conocimientos, personas y posibilidades que ofrece Brasil.','Dia 1 · Brasil de Origem':'Día 1 · Brasil de Origen','Dia 2 · Brasil que Cria':'Día 2 · Brasil que Crea','Arena de Saberes':'Arena de Saberes','Conhecimento que faz parte da jornada.':'Conocimiento que forma parte del viaje.','Uma narrativa, muitos encontros':'Una narrativa, muchos encuentros','Não é apenas sobre assistir.':'No se trata solo de mirar.',
      'Uma voz para ampliar o impacto.':'Una voz para ampliar el impacto.','A Embaixadora do Ane Cakes Fair representa os valores do evento, inspira a comunidade e ajuda a levar essa transformação ainda mais longe.':'La Embajadora de Ane Cakes Fair representa los valores del evento, inspira a la comunidad y ayuda a llevar esta transformación aún más lejos.','Em breve anunciaremos a embaixadora oficial da edição 2026.':'Pronto anunciaremos a la embajadora oficial de la edición 2026.','Quem será a escolhida?':'¿Quién será elegida?','Cinco nomes, uma grande expectativa. A revelação oficial da primeira embaixadora da Ane Cakes Fair vem aí.':'Cinco nombres, una gran expectativa. La revelación oficial de la primera embajadora de Ane Cakes Fair está por llegar.','Quero saber mais':'Quiero saber más',
      'Aprender':'Aprender','Praticar':'Practicar','Apresentar':'Presentar','Conectar':'Conectar','Origem':'Origen','Transformação':'Transformación','Criação':'Creación','Negócios':'Negocios','Experiência':'Experiencia','Destino':'Destino','Capacitação':'Formación','Profissionalização':'Profesionalización','Empreendedorismo':'Emprendimiento','Conhecer':'Conocer','Experimentar':'Experimentar','Compartilhar':'Compartir','Registrar':'Registrar'
    },
    pt:{}
  };

  function collect(){
    const root=document.body;if(!root)return [];
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue.trim()||SKIP.has(n.parentElement?.tagName)||n.parentElement?.closest('.project-language'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});
    const nodes=[];while(walker.nextNode()){const n=walker.currentNode;if(!originals.has(n))originals.set(n,n.nodeValue);nodes.push(n)}return nodes;
  }
  function translateAttributes(lang){
    document.querySelectorAll('[data-i18n-placeholder],[data-i18n-title],[data-i18n-aria-label],[data-i18n-alt]').forEach(el=>{
      [['data-i18n-placeholder','placeholder'],['data-i18n-title','title'],['data-i18n-aria-label','aria-label'],['data-i18n-alt','alt']].forEach(([a,target])=>{const key=el.getAttribute(a);if(key&&DICT[lang]?.[key]!==undefined)el.setAttribute(target,DICT[lang][key])});
    });
  }
  function apply(lang){
    if(!LANGS.includes(lang))lang='pt';
    localStorage.setItem('anecake-language',lang);
    document.documentElement.lang=lang==='pt'?'pt-BR':lang;
    const map=Object.assign({},DICT[lang]||{},EXTRA[lang]||{});
    collect().forEach(n=>{const key=normalize(originals.get(n)||'');const translated=map[key];n.nodeValue=translated!==undefined?preserve(originals.get(n),translated):originals.get(n)});
    document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(map[key]!==undefined)el.textContent=map[key]});
    translateAttributes(lang);
    document.querySelectorAll('.project-language-select').forEach(s=>s.value=lang);
    window.dispatchEvent(new CustomEvent('anecake:language',{detail:{lang}}));
  }
  async function load(){try{const r=await fetch('idiomas.json',{cache:'no-store'});DICT=await r.json()}catch(e){DICT={pt:{},en:{},es:{}}}boot()}
  function boot(){const select=document.querySelector('.project-language-select');if(!select)return setTimeout(boot,100);select.addEventListener('change',()=>apply(select.value));apply(localStorage.getItem('anecake-language')||'pt')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
  window.AneCakesLanguage={apply};
})();