/* Ane Cakes Fair — tradução nativa, sem Google Translate. */
(function(){
  const LANGS=['pt','en','es','fr','it'];
  let DICT={};
  const originals=new WeakMap();
  const SKIP=new Set(['SCRIPT','STYLE','NOSCRIPT','TEXTAREA','OPTION']);
  const normalize=s=>String(s||'').replace(/\s+/g,' ').trim();
  const preserve=(original,translated)=>{const lead=(original.match(/^\s*/)||[''])[0],trail=(original.match(/\s*$/)||[''])[0];return lead+translated+trail};

  /* Complementos para francês e italiano. Além das frases principais, há um
     fallback lexical para que textos novos do site também recebam tradução. */
  const EXTRA={
    en:{'Idioma':'Language','Escolha o idioma':'Choose language','Fechar imagem':'Close image','DIAS':'DAYS','HORAS':'HOURS','MINUTOS':'MINUTES','SEGUNDOS':'SECONDS'},
    es:{'Idioma':'Idioma','Escolha o idioma':'Elige el idioma','Fechar imagem':'Cerrar imagen','DIAS':'DÍAS','HORAS':'HORAS','MINUTOS':'MINUTOS','SEGUNDOS':'SEGUNDOS'},
    fr:{
      'Idioma':'Langue','Escolha o idioma':'Choisissez la langue','Fechar imagem':'Fermer l’image','DIAS':'JOURS','HORAS':'HEURES','MINUTOS':'MINUTES','SEGUNDOS':'SECONDES',
      '5ª EDIÇÃO · ILHÉUS, BAHIA · DA ORIGEM AO DESTINO':'5e ÉDITION · ILHÉUS, BAHIA · DE L’ORIGINE À LA DESTINATION',
      '5ª EDIÇÃO · ILHÉUS, BAHIA · 30 DE NOVEMBRO DE 2026':'5e ÉDITION · ILHÉUS, BAHIA · 30 NOVEMBRE 2026',
      'Confeitaria · cacau · território · pessoas':'Pâtisserie · cacao · territoire · personnes','Da origem ao destino.':'De l’origine à la destination.','Uma história para viver.':'Une histoire à vivre.',
      'Descobrir o Ane Cakes':'Découvrir Ane Cakes','Conhecer nossa história →':'Découvrir notre histoire →','mulheres capacitadas':'femmes formées','edições realizadas':'éditions réalisées','pessoas na rede':'personnes dans le réseau',
      'SABOR · CRIATIVIDADE · CONEXÃO · EXPERIÊNCIA':'SAVEUR · CRÉATIVITÉ · CONNEXION · EXPÉRIENCE','Eu vou chegar lá!':'J’y arriverai !','Começou na confeitaria.':'Tout a commencé avec la pâtisserie.','Descobriu uma cadeia inteira.':'Une chaîne entière a été découverte.',
      'Aprender':'Apprendre','Praticar':'Pratiquer','Apresentar':'Présenter','Conectar':'Connecter','Origem':'Origine','Transformação':'Transformation','Criação':'Création','Negócios':'Affaires','Experiência':'Expérience','Destino':'Destination','Capacitação':'Formation','Profissionalização':'Professionnalisation','Empreendedorismo':'Entrepreneuriat',
      'Uma história real':'Une histoire vraie','O impacto começa nas pessoas.':'L’impact commence avec les personnes.','A nova jornada':'Le nouveau voyage','O cacau conta essa história.':'Le cacao raconte cette histoire.','Ingredientes, produtores e território.':'Ingrédients, producteurs et territoire.','Processos, indústria, tecnologia e valor.':'Processus, industrie, technologie et valeur.','Chefs, confeiteiros, chocolatiers e empreendedores.':'Chefs, pâtissiers, chocolatiers et entrepreneurs.',
      'O fio condutor':'Le fil conducteur','Do ingrediente à criação':'De l’ingrédient à la création','A experiência':'L’expérience','Veja. Aprenda. Prove. Descubra.':'Voyez. Apprenez. Goûtez. Découvrez.','Celebrar':'Célébrer','Experimentar':'Expérimenter','Descubra mais':'Découvrez davantage','Continue a jornada':'Continuez le voyage','A feira termina. A descoberta continua.':'La foire se termine. La découverte continue.',
      'Local previsto':'Lieu prévu','Mulheres em formação':'Femmes en formation','Público estimado':'Public estimé','Formato':'Format','Feira · palestras · workshops · degustações':'Foire · conférences · ateliers · dégustations','Capacitação que vira profissão.':'Une formation qui devient une profession.','Talento que vira história.':'Un talent qui devient une histoire.',
      'Mulheres que transformam':'Des femmes qui transforment','Talento não precisa ficar escondido.':'Le talent n’a pas besoin de rester caché.','Precisa encontrar oportunidade.':'Il doit trouver une opportunité.','Da sala de aula para o mercado.':'De la salle de classe au marché.','Nossa rede':'Notre réseau','Conhecer histórias →':'Découvrir des histoires →','Noite de certificação':'Soirée de certification',
      'O conceito central':'Le concept central','Da origem ao destino: conectando os sabores do Brasil ao mundo.':'De l’origine à la destination : relier les saveurs du Brésil au monde.','A jornada Ane Cakes':'Le voyage Ane Cakes','Fruto':'Fruit','Role para explorar':'Faites défiler pour explorer','Uma cadeia, muitas histórias':'Une chaîne, de nombreuses histoires','Conhecer o território →':'Découvrir le territoire →','NARRATIVA INTERATIVA':'RÉCIT INTERACTIF','▶ Ouvir a narrativa':'▶ Écouter le récit',
      'Cada resultado começa com uma história.':'Chaque résultat commence par une histoire.','Histórias que inspiram':'Des histoires qui inspirent','Quando a capacitação encontra um novo caminho.':'Quand la formation rencontre un nouveau chemin.','Em formação':'En formation','Talento em prática':'Le talent en pratique','Profissionalização':'Professionnalisation','Conhecimento que vira negócio':'Le savoir qui devient une activité',
      'Parceiros':'Partenaires','Equipe':'Équipe','Caravanas':'Caravanes','Expositores':'Exposants','Batalha Doce':'Bataille Sucrée','Roteiro':'Programme','Roteiro do Evento':'Programme de l’événement','Embaixadora':'Ambassadrice','Início':'Accueil','Quero ser parceiro':'Je veux être partenaire','Quero participar →':'Je veux participer →','Quero expor →':'Je veux exposer →','Quero saber mais':'Je veux en savoir plus',
      'Dois dias, uma jornada.':'Deux jours, un voyage.','Dia 1 · Brasil de Origem':'Jour 1 · Brésil d’origine','Dia 2 · Brasil que Cria':'Jour 2 · Brésil qui crée','Arena de Saberes':'Arène des savoirs','Conhecimento que faz parte da jornada.':'Un savoir qui fait partie du voyage.','Uma narrativa, muitos encontros':'Un récit, de nombreuses rencontres','Não é apenas sobre assistir.':'Il ne s’agit pas seulement de regarder.',
      'Uma voz para ampliar o impacto.':'Une voix pour amplifier l’impact.','Quem será a escolhida ?':'Qui sera choisie ?','Quem será a escolhida?':'Qui sera choisie ?','Em breve anunciaremos a embaixadora oficial da edição 2026.':'Nous annoncerons bientôt l’ambassadrice officielle de l’édition 2026.','Cinco nomes, uma grande expectativa.':'Cinq noms, une grande attente.',
      'Prepare-se para criar.':'Préparez-vous à créer.','Inscrições e regulamento em breve':'Inscriptions et règlement prochainement','Não é apenas uma competição.':'Ce n’est pas seulement une compétition.','Onde o talento encontra a criação.':'Là où le talent rencontre la création.','Talento que vira repertório.':'Un talent qui devient un savoir-faire.'
    },
    it:{
      'Idioma':'Lingua','Escolha o idioma':'Scegli la lingua','Fechar imagem':'Chiudi immagine','DIAS':'GIORNI','HORAS':'ORE','MINUTOS':'MINUTI','SEGUNDOS':'SECONDI',
      '5ª EDIÇÃO · ILHÉUS, BAHIA · DA ORIGEM AO DESTINO':'5ª EDIZIONE · ILHÉUS, BAHIA · DALL’ORIGINE ALLA DESTINAZIONE','5ª EDIÇÃO · ILHÉUS, BAHIA · 30 DE NOVEMBRO DE 2026':'5ª EDIZIONE · ILHÉUS, BAHIA · 30 NOVEMBRE 2026',
      'Confeitaria · cacau · território · pessoas':'Pasticceria · cacao · territorio · persone','Da origem ao destino.':'Dall’origine alla destinazione.','Uma história para viver.':'Una storia da vivere.','Descobrir o Ane Cakes':'Scoprire Ane Cakes','Conhecer nossa história →':'Conoscere la nostra storia →','mulheres capacitadas':'donne formate','edições realizadas':'edizioni realizzate','pessoas na rede':'persone nella rete',
      'SABOR · CRIATIVIDADE · CONEXÃO · EXPERIÊNCIA':'SAPORE · CREATIVITÀ · CONNESSIONE · ESPERIENZA','Eu vou chegar lá!':'Ci arriverò!','Começou na confeitaria.':'È iniziato con la pasticceria.','Descobriu uma cadeia inteira.':'Ha scoperto un’intera filiera.',
      'Aprender':'Imparare','Praticar':'Praticare','Apresentar':'Presentare','Conectar':'Connettere','Origem':'Origine','Transformação':'Trasformazione','Criação':'Creazione','Negócios':'Business','Experiência':'Esperienza','Destino':'Destinazione','Capacitação':'Formazione','Profissionalização':'Professionalizzazione','Empreendedorismo':'Imprenditorialità',
      'Uma história real':'Una storia vera','O impacto começa nas pessoas.':'L’impatto inizia dalle persone.','A nova jornada':'Il nuovo viaggio','O cacau conta essa história.':'Il cacao racconta questa storia.','Ingredientes, produtores e território.':'Ingredienti, produttori e territorio.','Processos, indústria, tecnologia e valor.':'Processi, industria, tecnologia e valore.','Chefs, confeiteiros, chocolatiers e empreendedores.':'Chef, pasticceri, cioccolatieri e imprenditori.',
      'O fio condutor':'Il filo conduttore','Do ingrediente à criação':'Dall’ingrediente alla creazione','A experiência':'L’esperienza','Veja. Aprenda. Prove. Descubra.':'Guarda. Impara. Assaggia. Scopri.','Celebrar':'Celebrare','Experimentar':'Sperimentare','Descubra mais':'Scopri di più','Continue a jornada':'Continua il viaggio','A feira termina. A descoberta continua.':'La fiera finisce. La scoperta continua.',
      'Local previsto':'Luogo previsto','Mulheres em formação':'Donne in formazione','Público estimado':'Pubblico stimato','Formato':'Formato','Feira · palestras · workshops · degustações':'Fiera · conferenze · workshop · degustazioni','Capacitação que vira profissão.':'Una formazione che diventa professione.','Talento que vira história.':'Un talento che diventa storia.',
      'Mulheres que transformam':'Donne che trasformano','Talento não precisa ficar escondido.':'Il talento non deve rimanere nascosto.','Precisa encontrar oportunidade.':'Deve trovare un’opportunità.','Da sala de aula para o mercado.':'Dall’aula al mercato.','Nossa rede':'La nostra rete','Conhecer histórias →':'Scopri le storie →','Noite de certificação':'Serata di certificazione',
      'O conceito central':'Il concetto centrale','Da origem ao destino: conectando os sabores do Brasil ao mundo.':'Dall’origine alla destinazione: collegare i sapori del Brasile al mondo.','A jornada Ane Cakes':'Il viaggio Ane Cakes','Fruto':'Frutto','Role para explorar':'Scorri per esplorare','Uma cadeia, muitas histórias':'Una filiera, molte storie','Conhecer o território →':'Scopri il territorio →','NARRATIVA INTERATIVA':'NARRAZIONE INTERATTIVA','▶ Ouvir a narrativa':'▶ Ascolta la narrazione',
      'Cada resultado começa com uma história.':'Ogni risultato inizia con una storia.','Histórias que inspiram':'Storie che ispirano','Quando a capacitação encontra um novo caminho.':'Quando la formazione incontra una nuova strada.','Em formação':'In formazione','Talento em prática':'Talento in pratica','Profissionalização':'Professionalizzazione','Conhecimento que vira negócio':'La conoscenza che diventa impresa',
      'Parceiros':'Partner','Equipe':'Squadra','Caravanas':'Carovane','Expositores':'Espositori','Batalha Doce':'Battaglia Dolce','Roteiro':'Programma','Roteiro do Evento':'Programma dell’evento','Embaixadora':'Ambasciatrice','Início':'Home','Quero ser parceiro':'Voglio essere partner','Quero participar →':'Voglio partecipare →','Quero expor →':'Voglio esporre →','Quero saber mais':'Voglio saperne di più',
      'Dois dias, uma jornada.':'Due giorni, un viaggio.','Dia 1 · Brasil de Origem':'Giorno 1 · Brasile d’origine','Dia 2 · Brasil que Cria':'Giorno 2 · Brasile che crea','Arena de Saberes':'Arena dei saperi','Conhecimento que faz parte da jornada.':'La conoscenza fa parte del viaggio.','Uma narrativa, muitos encontros':'Una narrazione, molti incontri','Não é apenas sobre assistir.':'Non si tratta solo di guardare.',
      'Uma voz para ampliar o impacto.':'Una voce per ampliare l’impatto.','Quem será a escolhida?':'Chi sarà scelta?','Em breve anunciaremos a embaixadora oficial da edição 2026.':'Presto annunceremo l’ambasciatrice ufficiale dell’edizione 2026.','Cinco nomes, uma grande expectativa.':'Cinque nomi, una grande attesa.',
      'Prepare-se para criar.':'Preparati a creare.','Inscrições e regulamento em breve':'Iscrizioni e regolamento prossimamente','Não é apenas uma competição.':'Non è solo una competizione.','Onde o talento encontra a criação.':'Dove il talento incontra la creazione.','Talento que vira repertório.':'Un talento che diventa esperienza.'
    },
    pt:{}
  };

  /* Fallback lexical para conteúdo novo que ainda não esteja no JSON. */
  const WORDS={
    fr:{' e ':' et ',' de ':' de ',' da ':' de ',' do ':' du ',' dos ':' des ',' das ':' des ',' para ':' pour ',' com ':' avec ',' por ':' par ',' uma ':' une ',' um ':' un ',' o ':' le ',' a ':' la ',' os ':' les ',' as ':' les ',' que ':' qui ',' em ':' à ',' no ':' dans le ',' na ':' dans la ',' ao ':' au ',' aos ':' aux ',' são ':' sont ',' é ':' est ',' não ':' ne ',' mais ':' plus ',' também ':' aussi ',' história':' histoire','histórias':'histoires','pessoas':'personnes','mulheres':'femmes','homens':'hommes','projeto':'projet','evento':'événement','feira':'foire','sabores':'saveurs','sabor':'saveur','confeitaria':'pâtisserie','cacau':'cacao','território':'territoire','origem':'origine','destino':'destination','talento':'talent','oportunidade':'opportunité','conhecimento':'connaissance','trabalho':'travail','mercado':'marché','negócio':'activité','negócios':'activités','parceiros':'partenaires','equipe':'équipe','equipe':'équipe','descobrir':'découvrir','conhecer':'connaître','aprender':'apprendre','criar':'créer','participar':'participer','experiência':'expérience','jornada':'voyage','dia':'jour','dias':'jours','público':'public','formação':'formation','profissional':'professionnel','profissionais':'professionnels','produção':'production','produtores':'producteurs','produto':'produit','produtos':'produits','Brasil':'Brésil','mundo':'monde'},
    it:{' e ':' e ',' de ':' di ',' da ':' dalla ',' do ':' del ',' dos ':' dei ',' das ':' delle ',' para ':' per ',' com ':' con ',' por ':' da ',' uma ':' una ',' um ':' un ',' o ':' il ',' a ':' la ',' os ':' i ',' as ':' le ',' que ':' che ',' em ':' in ',' no ':' nel ',' na ':' nella ',' ao ':' al ',' aos ':' agli ',' são ':' sono ',' é ':' è ',' não ':' non ',' mais ':' più ',' também ':' anche ',' história':' storia','histórias':'storie','pessoas':'persone','mulheres':'donne','homens':'uomini','projeto':'progetto','evento':'evento','feira':'fiera','sabores':'sapori','sabor':'sapore','confeitaria':'pasticceria','cacau':'cacao','território':'territorio','origem':'origine','destino':'destinazione','talento':'talento','oportunidade':'opportunità','conhecimento':'conoscenza','trabalho':'lavoro','mercado':'mercato','negócio':'attività','negócios':'attività','parceiros':'partner','equipe':'squadra','descobrir':'scoprire','conhecer':'conoscere','aprender':'imparare','criar':'creare','participar':'partecipare','experiência':'esperienza','jornada':'viaggio','dia':'giorno','dias':'giorni','público':'pubblico','formação':'formazione','profissional':'professionale','profissionais':'professionisti','produção':'produzione','produtores':'produttori','produto':'prodotto','produtos':'prodotti','Brasil':'Brasile','mundo':'mondo'}
  };
  function lexical(text,lang){if(lang==='pt'||!WORDS[lang])return text;let s=' '+text+' ';for(const [a,b] of Object.entries(WORDS[lang]))s=s.split(a).join(b);return s.trim()}

  function collect(){const root=document.body;if(!root)return [];const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||!n.nodeValue.trim()||SKIP.has(p.tagName)||p.closest('.project-language'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const out=[];while(w.nextNode()){const n=w.currentNode;if(!originals.has(n))originals.set(n,n.nodeValue);out.push(n)}return out}
  function translateAttributes(lang,map){document.querySelectorAll('[data-i18n-placeholder],[data-i18n-title],[data-i18n-aria-label],[data-i18n-alt]').forEach(el=>[['data-i18n-placeholder','placeholder'],['data-i18n-title','title'],['data-i18n-aria-label','aria-label'],['data-i18n-alt','alt']].forEach(([a,target])=>{const key=el.getAttribute(a);if(key&&map[normalize(key)]!==undefined)el.setAttribute(target,map[normalize(key)])}))}
  function apply(lang){if(!LANGS.includes(lang))lang='pt';const map=Object.assign({},DICT[lang]||{},EXTRA[lang]||{});collect().forEach(n=>{const o=originals.get(n),key=normalize(o),t=map[key];n.nodeValue=t!==undefined?preserve(o,t):preserve(o,lexical(key,lang))});document.querySelectorAll('[data-i18n]').forEach(el=>{const key=normalize(el.getAttribute('data-i18n')),t=map[key];if(t!==undefined)el.textContent=t});translateAttributes(lang,map);document.documentElement.lang=lang;localStorage.setItem('anecake-language',lang);document.dispatchEvent(new CustomEvent('anecake:language',{detail:{lang}}))}
  async function boot(){try{const r=await fetch('idiomas.json',{cache:'no-cache'});if(r.ok)DICT=await r.json()}catch(e){}const select=document.getElementById('project-language-select');if(select){select.innerHTML='';[['pt','🇧🇷 Português'],['en','🇺🇸 English'],['es','🇪🇸 Español'],['fr','🇫🇷 Français'],['it','🇮🇹 Italiano']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;select.appendChild(o)});select.addEventListener('change',()=>apply(select.value))}const saved=localStorage.getItem('anecake-language')||'pt';if(select)select.value=saved;apply(saved)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();