/* Ane Cakes Fair — tradução nativa, sem Google Translate. */
(function(){
  const LANGS=['pt','en','es','fr','it'];
  let DICT={};
  const originals=new WeakMap();
  const SKIP=new Set(['SCRIPT','STYLE','NOSCRIPT','TEXTAREA','OPTION']);
  const normalize=s=>String(s||'').replace(/\s+/g,' ').trim();
  const preserve=(original,translated)=>{const lead=(original.match(/^\s*/)||[''])[0],trail=(original.match(/\s*$/)||[''])[0];return lead+translated+trail};
  const EXTRA={en:{'Idioma':'Language','Escolha o idioma':'Choose language','Fechar imagem':'Close image','DIAS':'DAYS','HORAS':'HOURS','MINUTOS':'MINUTES','SEGUNDOS':'SECONDS'},es:{'Idioma':'Idioma','Escolha o idioma':'Elige el idioma','Fechar imagem':'Cerrar imagen','DIAS':'DÍAS','HORAS':'HORAS','MINUTOS':'MINUTOS','SEGUNDOS':'SEGUNDOS'},fr:{'Idioma':'Langue','Escolha o idioma':'Choisissez la langue','Fechar imagem':'Fermer l’image','DIAS':'JOURS','HORAS':'HEURES','MINUTOS':'MINUTES','SEGUNDOS':'SECONDES'},it:{'Idioma':'Lingua','Escolha o idioma':'Scegli la lingua','Fechar imagem':'Chiudi immagine','DIAS':'GIORNI','HORAS':'ORE','MINUTOS':'MINUTI','SEGUNDOS':'SECONDI'},pt:{}};
  function collect(){const root=document.body;if(!root)return [];const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||!n.nodeValue.trim()||SKIP.has(p.tagName)||p.closest('.project-language'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const out=[];while(w.nextNode()){const n=w.currentNode;if(!originals.has(n))originals.set(n,n.nodeValue);out.push(n)}return out}
  function translateAttributes(lang,map){document.querySelectorAll('[data-i18n-placeholder],[data-i18n-title],[data-i18n-aria-label],[data-i18n-alt]').forEach(el=>[['data-i18n-placeholder','placeholder'],['data-i18n-title','title'],['data-i18n-aria-label','aria-label'],['data-i18n-alt','alt']].forEach(([a,target])=>{const key=el.getAttribute(a);if(key&&map[normalize(key)]!==undefined)el.setAttribute(target,map[normalize(key)])}))}
  function apply(lang){if(!LANGS.includes(lang))lang='pt';const map=Object.assign({},DICT[lang]||{},EXTRA[lang]||{});collect().forEach(n=>{const o=originals.get(n),t=map[normalize(o)];n.nodeValue=t!==undefined?preserve(o,t):o});document.querySelectorAll('[data-i18n]').forEach(el=>{const t=map[normalize(el.getAttribute('data-i18n'))];if(t!==undefined)el.textContent=t});translateAttributes(lang,map);document.documentElement.lang=lang;localStorage.setItem('anecake-language',lang);document.dispatchEvent(new CustomEvent('anecake:language',{detail:{lang}}))}
  async function boot(){try{const r=await fetch('idiomas.json',{cache:'no-cache'});if(r.ok)DICT=await r.json()}catch(e){}const select=document.getElementById('project-language-select');if(select){select.innerHTML='';[['pt','🇧🇷 Português'],['en','🇺🇸 English'],['es','🇪🇸 Español'],['fr','🇫🇷 Français'],['it','🇮🇹 Italiano']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;select.appendChild(o)});select.addEventListener('change',()=>apply(select.value))}const saved=localStorage.getItem('anecake-language')||'pt';if(select)select.value=saved;apply(saved)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();